### ISSUE TITLE
反馈

### ISSUE THREAD

**Issue by ChrisLeeGit** [i-square/learnPython#2]
1. dict_set.py
    1. Python 支持两种引号，所以你可以：`print("d['Michael'] =", d['Michael'])`
    1. 一般如果直接创建含有已知序列的集合，可以：`s = {1, 1, 2, 2, 3, 3}`，你那种写法，会让 Python 解释器先创建一个匿名的 `list` 类型，然后再被转换成 `set` 类型。当需要对一个 `list` 等转换成集合时再用 `s = set(L)`

1. hello.py
   1. 建议用新式的 `"".format()` 语法替代 `print('Hi, %s, you have $%.2e.' % (name, 1584215))` 旧的格式化方法，很好用

1. list_tuple.py
    1. `ttuple = ('Michael', 'Bob', 'Tracy', tlist)`，建议不要在 `tuple` 中放 `mutable` 的变量，来自 `Fluent Python` 的原话：`[Page 42]Putting mutable items in tuples is not a good idea`，因为在执行诸如 `ttuple[-1] += L` 的时候可能会有诡异的问题发生，可以看下面的例子：实际上，这里 ttuple[-1] 的确指向 list，list 是可以 `mutable` 的，所以，列表加列表是对的，但是 ttuple[-1] = new_list 的时候就不对了，因为 tuple 是 `unmutable` 的。
![](http://blog.chriscabin.com/wp-content/uploads/2017/05/Snip20170526_1.png)

**Comment by i-square** [comment]
1. 两种引号用来避免转义，哈哈，学到了
2. 用了新式的了
3. 那个就是为了试试，实际肯定不这么干了
